#!/bin/bash

top_dir=`git rev-parse --show-toplevel`
src_dir=${top_dir}/src
bin_dir=${src_dir}/vendor/bin

valid=true

if git rev-parse --verify HEAD > /dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for file in `git diff-index --name-status ${against} ${src_dir} | grep -E '^[AUM].*\.php$' | cut -c3-`; do
    if php -l ${file} 1> /dev/null; then
        (cd ${src_dir} && php composer.phar fix -- ${top_dir}/${file})

        # Detect mess
        if (${bin_dir}/phpmd ${file} text ${src_dir}/phpmd.xml); then
            git add ${file}
        else
            valid=false
        fi
    else
        valid=false
    fi
done

if ! ${valid}; then
    echo
    echo "Something bad is detected."
    echo "Commit cancelled."

    exit 1;
fi
